accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('confirm/', views.confirm_email, name='confirm_email'),
    path('confirm/sent/', views.email_confirm_sent, name='email_confirm_sent'),

    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('tag/<int:tag_pk>', views.article_list, name='article_list_by_tag'),
    path('', views.article_list, name='article_list'),
    path('create/', views.article_create, name='article_create'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
    path('<int:pk>/update/', views.article_update, name='article_update'),
    path('<int:pk>/delete/', views.article_delete, name='article_delete'),

    path('<int:article_pk>/comment/create/', views.comment_create, name='comment_create'),

    path('<int:pk>/like/', views.article_like, name='article_like'),
]

piro_remind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings


class EmailConfirm(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='email_confirm',
        on_delete=models.CASCADE,
    )
    key = models.CharField(max_length=60)
    is_confirmed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        upload_to='profile/%Y/%m/%d/',
        blank=True,
        null=True,
    )
    birth_day = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True)

    def image_url(self):
        if self.image:
            image_url = self.image.url
        else:
            image_url = '/static/img/default_profile_image.jpg'
        return image_url

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
)

from .models import Profile


class AuthForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "아이디 또는 패스워드가 틀렸습니다.",
        'inactive': "탈퇴한 계정입니다.",
    }


class SignupForm(UserCreationForm):
    error_messages = {
        'password_mismatch': '패스워드가 일치하지 않습니다.',
    }

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email is not None and email.split('@')[1] != 'snu.ac.kr':
            raise forms.ValidationError('snu 이메일만 가입이 가능합니다.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class SignupProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', 'image', )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', )

accounts/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
)
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

from .models import EmailConfirm, Profile
from .forms import (
    AuthForm,
    SignupForm,
    SignupProfileForm,
    ProfileForm,
)
from .utils import generate_random_string


def login(request):
    form = AuthForm(request, request.POST or None)
    if request.method == "POST" and form.is_valid():
        return login_and_redirect_next(request, form.get_user())

    ctx = {
        'form': form,
    }
    return render(request, 'accounts/login.html', ctx)


def logout(request):
    auth_logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


def signup(request):
    signup_form = SignupForm(request.POST or None)
    profile_form = SignupProfileForm(request.POST or None, prefix='profile')
    if request.method == 'POST':
        if signup_form.is_valid() and profile_form.is_valid():
            user = signup_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return login_and_redirect_next(request, user)
    ctx = {
        'signup_form': signup_form,
        'profile_form': profile_form,
    }
    return render(request, 'accounts/signup.html', ctx)


def login_and_redirect_next(request, user):
    if EmailConfirm.objects.filter(user=user, is_confirmed=True).exists():
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user)
        auth_login(request, user)
        next_url = request.GET.get('next') or settings.LOGIN_REDIRECT_URL
        return redirect(next_url)
    else:
        send_confirm_mail(user)
        return redirect(reverse('accounts:email_confirm_sent'))


def send_confirm_mail(user):
    try:
        email_confirm = EmailConfirm.objects.get(user=user)
    except EmailConfirm.DoesNotExist:
        email_confirm = EmailConfirm.objects.create(
            user=user,
            key=generate_random_string(length=60),
        )

    url = '{0}{1}?key={2}'.format(
        'http://localhost:8000',
        reverse('accounts:confirm_email'),
        email_confirm.key,
    )
    html = '<p>계속하시려면 아래 링크를 눌러주세요.</p><a href="{0}">인증하기</a>'.format(url)
    send_mail(
        '인증 메일입니다.',
        '',
        settings.EMAIL_HOST_USER,
        [user.email],
        html_message=html,
    )


def email_confirm_sent(request):
    return render(request, 'accounts/email_confirm_sent.html')


def confirm_email(request):
    key = request.GET.get('key')
    email_confirm = get_object_or_404(EmailConfirm, key=key, is_confirmed=False)
    email_confirm.is_confirmed = True
    email_confirm.save()
    return login_and_redirect_next(request, email_confirm.user)


def profile_detail(request, username):
    ctx = {
        'profile': get_object_or_404(Profile, user__username=username),
    }
    return render(request, 'accounts/profile_detail.html', ctx)


@login_required
def profile_update(request):
    form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=request.user.profile,
    )
    if request.method == 'POST' and form.is_valid():
        profile = form.save()
        return redirect(reverse('accounts:profile_detail', kwargs={
            'username': profile.user.username,
        }))
    ctx = {
        'form': form,
    }
    return render(request, 'accounts/profile_create.html', ctx)

accounts/templates/accounts/email_confirm_sent.html
{% extends 'base.html' %}

{% block content %}
<div class="row margin-top-200">
  <div class="col s12 l10 offset-l1">
    <h4>인증 메일을 발송하였습니다. 회원 가입시 사용한 이메일을 확인해주세요.</h4>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row margin-top-200">
  <div class="col s12 l10 offset-l1">
    {% if request.user.is_authenticated %}
    <h1>{{ request.user.username }}님 안녕하세요~</h1>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-block">Log out</button>
    </form>
    {% else %}
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-block">로그인</button>
    </form>
    <a href="{% url 'accounts:signup' %}" type="button" class="btn btn-block" style="margin-top: 10px;">회원가입</a>
    {% endif %}
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile_create.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s12 l10 offset-l1">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">제출</button>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s12 l10 offset-l1">
    <div class="center-align">
      <h3>{{ profile.user }}</h3>
      <img class="responsive-img profile_image" src="{{ profile.image_url }}">
      <p>생일 : {{ profile.birth_day|date:"Y.m.d."|default:"미입력" }}</p>
      <p>자기소개 : {{ profile.description|default:"미입력" }}</p>
      {% if request.user.profile == profile %}
      <a href="{% url 'accounts:profile_update' %}" type="button" class="btn">프로필 수정</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="row margin-top-200">
  <div class="col s12 l10 offset-l1">
    {% if request.user.is_authenticated %}
    <h1>이미 로그인하셨습니다.</h1>
    {% else %}
    <form method="POST">
      {% csrf_token %}
      <h4>필수 정보</h4>
      {{ signup_form.as_p }}
      <h4>프로필 정보</h4>
      {{ profile_form.as_p }}
      <button type="submit" class="btn btn-block">회원가입</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}