accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('confirm/', views.confirm_email, name='confirm_email'),
    path('confirm/sent/', views.email_confirm_sent, name='email_confirm_sent'),

    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('tag/<int:tag_pk>', views.article_list, name='article_list_by_tag'),
    path('', views.article_list, name='article_list'),
    path('create/', views.article_create, name='article_create'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
    path('<int:pk>/update/', views.article_update, name='article_update'),
    path('<int:pk>/delete/', views.article_delete, name='article_delete'),

    path('<int:article_pk>/comment/create/', views.comment_create, name='comment_create'),

    path('<int:pk>/like/', views.article_like, name='article_like'),
]

piro_remind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Tag(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(
        max_length=30,
        verbose_name='제목',
    )
    content = models.TextField(verbose_name='내용')

    liker_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='liked_article_set',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # m2m 에서 blank=True 설정하면 모델폼에서 폼 필드 렌더링할 때
    # required 옵션이 빠짐.
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return '{0}.{1}'.format(self.pk, self.title)

    def get_absolute_url(self):
        return reverse('core:article_detail', kwargs={
            'pk': self.pk,
        })


class Comment(models.Model):
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    content = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

core/forms.py
from django import forms

from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('liker_set', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('article', 'author', )

    # def __init__(self, *args, **kwargs):
    #     self.user = kwargs.pop('user')
    #     self.article = kwargs.pop('article')
    #     super().__init__(*args, **kwargs)

    # def clean(self):
    #     comment_count = self.user.comment_set.filter(article=self.article).count()
    #     if comment_count >= 5:
    #         raise forms.ValidationError('댓글은 5회만 남기실 수 있습니다.')

    # def save(self):
    #     comment = super().save(commit=False)
    #     comment.article = self.article
    #     comment.author = self.user
    #     comment.save()
    #     return comment

core/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.urls import reverse
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string

from .models import Article, Tag
from .forms import ArticleForm, CommentForm


MAX_COMMENT_COUNT = 100


def article_list(request, tag_pk=None):
    if tag_pk is not None:
        article_list = Article.objects.filter(tag__pk=tag_pk)
        # get_object_or_404 사용하는게 좋음.
        try:
            tag = Tag.objects.get(pk=tag_pk)
        except Tag.DoesNotExist:
            raise Http404('없는 Tag입니다.')
    else:
        article_list = Article.objects.all()
        tag = None

    ctx = {
        'article_list': article_list,
        'tag_list': Tag.objects.all(),
        'tag_selected': tag,
    }
    return render(request, 'core/article_list.html', ctx)


# @login_required
# def article_detail(request, pk):
#     article = get_object_or_404(Article, pk=pk)
#     comment_form = CommentForm(
#         request.POST or None,
#         article=article,
#         user=request.user,
#     )
#     if request.method == "POST" and comment_form.is_valid():
#         comment_form.save()
#         return redirect(article.get_absolute_url())

#     ctx = {
#         'article': article,
#         'comment_form': comment_form,
#         'did_like_article': article.liker_set.filter(pk=request.user.pk),
#     }

#     return render(request, 'core/article_detail.html', ctx)


@login_required
def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_count = article.comment_set.filter(author=request.user).count()
    ctx = {
        'article': article,
        'comment_form': CommentForm(),
        'did_like_article': article.liker_set.filter(pk=request.user.pk),
        'can_write_comment': comment_count < MAX_COMMENT_COUNT,
    }
    return render(request, 'core/article_detail.html', ctx)


@login_required
def comment_create(request, article_pk):
    if request.POST:
        article = Article.objects.get(pk=article_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()

            return render(request, 'core/comment.html', {
                'comment': comment,
            })

    return HttpResponse(status=405)


@login_required
def article_create(request):
    form = ArticleForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


@login_required
def article_update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = ArticleForm(request.POST or None, instance=article)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


# 이렇게 하나로 쓸 수도 있다. 상황에 맞게 하면 됨.
@login_required
def article_create_or_update(request, pk=None):
    if pk is not None:
        article = get_object_or_404(Article, pk=pk)
    else:
        article = None
    form = ArticleForm(request.POST or None, instance=article)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


@login_required
def article_delete(request, pk):
    if request.method == "POST":
        article = get_object_or_404(Article, pk=pk)
        article.delete()
        return redirect(reverse('core:article_list'))
    else:
        return HttpResponse(status=400)


@login_required
def article_like(request, pk):
    if request.method == "POST":
        article = get_object_or_404(Article, pk=pk)

        if request.user.liked_article_set.filter(pk=pk).exists():
            article.liker_set.remove(request.user)
        else:
            article.liker_set.add(request.user)

        ctx = {
            'did_like_article': article.liker_set.filter(pk=request.user.pk).exists(),
            'article': article,
        }
        return render(request, 'core/article_like_button.html', ctx)

    else:
        return HttpResponse(status=400)

core/templates/core/article_create.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
  <div class="col s12 l10 offset-l1" style="text-align: center; margin-top: 100px;">
    <h2>게시판 글쓰기</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">제출</button>
    </form>
  </div>
  <script>
    $(document).ready(function() {
      $('select').material_select();
    });
  </script>
</div>
{% endblock %}

core/templates/core/article_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col s12 l10 offset-l1">
        <!-- 본문 영역 -->
        <div style="padding: 80px 0 30px 0; margin-bottom: 50px;">
            <h2 style="text-align: center; color: #565656;">{{ article.title }}</h2>
            <div style="text-align: right;
                        margin-top: 30px;
                        margin-right: 10px;
                        font-size: 12px;">
                <span>{{ article.created_at|date:"Y.m.d h:i A" }}</span><br />
                <a href="{% url 'accounts:profile_detail' 'kaske' %}">Kaske</a>
            </div>
        </div>
        <div style="font-size: 13px; line-height: 18px; color: #565656;">
            <p>{{ article.content }}</p>
        </div>
        <div id="tag_area" style="margin: 20px 0;">
            {% for tag in article.tag.all %}
            <div class="chip">{{ tag.name }}</div>
            {% endfor %}
        </div>
        <div id="like_button_wrapper">
            <a id="like_button" href="{% url 'core:article_like' article.pk %}">
                {% include 'core/article_like_button.html' %}
            </a>
            <script>
                $('#like_button').click(function(e) {
                    var self = $(this);
                    var url = self.attr('href');

                    $.post(url)
                        .done(function(r) {
                            self.html(r);
                        })
                        .fail(function() {
                            alert('오류가 발생했습니다. 다시 해보세요.');
                        });

                    return false;
                });
            </script>
        </div>
        <!-- 본문 영역 끝 -->

        <a href="{% url 'core:article_list' %}" class="waves-effect waves-light btn">목록으로</a>

        <div style="float: right;">
            <a href="{% url 'core:article_update' article.pk %}" class="waves-effect waves-light btn">수정</a>
            <form id="article_delete_form" action="{% url 'core:article_delete' article.pk %}" method="POST" style="display: inline-block;">
                {% csrf_token %}
                <button type="submit" class="waves-effect waves-light btn">삭제</button>
            </form>
            <script>
                $('#article_delete_form').submit(function(e) {
                    if (!confirm('지우시겠습니까?')) {
                        e.preventDefault();
                    }
                });
            </script>
        </div>

        <!-- 댓글 영역 -->
        <div class="comment_area">
            <h4>댓글</h4>
                <div class="comment_form_area">
                    <form id="comment_form" class="{% if not can_write_comment %}hidden{% endif %}" method="POST">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        <button type="submit" class="waves-effect waves-light btn">작성</button>
                    </form>
                    <script>
                        $('#comment_form').submit(function(e) {
                            e.preventDefault();

                            var url = '{% url "core:comment_create" article.pk %}';
                            var data = {
                                content: $('input[name="content"]').val(),
                            };
                            $.post(url, data)
                                .done(function(r) {
                                    $('#comment_list').append(r);
                                })
                                .fail(function(r) {
                                    alert('에러가 발생했습니다. 다시 한번 시도해보세요. 지속적으로 발생시 연락 부탁드립니다.');
                                });

                        })
                    </script>
                    <p id="max_comment_error_msg" class="{% if can_write_comment %}hidden{% endif %}">댓글을 남기실 수 없습니다. 유저당 한 글에 5번만 댓글을 달 수 있습니다.</p>
                </script>
            {% if article.comment_set.exists %}
            <ul id="comment_list">
                {% for comment in article.comment_set.all %}
                    {% include 'core/comment.html' %}
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <!-- 댓글 영역 끝 -->
    </div>
</div>
{% endblock %}

core/templates/core/article_like_button.html
<button class="btn {% if did_like_article %}liked{% endif %}">추천 {{ article.liker_set.count }}</button>

core/templates/core/article_list.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
  <div class="col s12 l10 offset-l1">
    <div id="tag_list">
      {% if tag_list %}
        <a href="{% url 'core:article_list' %}">
          <div class="chip">전체 목록</div>
        </a>
        {% for tag in tag_list %}
        <a href="{% url 'core:article_list_by_tag' tag.pk %}">
          <div class="chip {% if tag == tag_selected %}selected{% endif %}">
              {{ tag.name }}
          </div>
        </a>
        {% endfor %}
      {% endif %}
    </div>
    <div class="collection">
      {% for article in article_list %}
      <a class="collection-item" id="article_{{ article.pk }}" href="{% url 'core:article_detail' article.pk %}">{{ article.title }}</a>
      {% empty %}
      <li class="collection-item">게시글이 없습니다.</li>
      {% endfor %}
    </div>

    <a id="create_button" href="{% url 'core:article_create' %}" class="waves-effect waves-light btn">글쓰기</a>
  </div>
</div>
{% endblock %}

core/templates/core/comment.html
<li style="margin: 30px 0;">
  <div style="font-size: 17px; font-weight: bold;">
    <a href="{% url 'accounts:profile_detail' comment.author.username %}">{{ comment.author }}</a>
  </div>
  <div style="margin: 10px 0;">
    <span>{{ comment.content }}</span>
    <span>{{ comment.created_at|date:"Y.m.d h:i A"}}</span>
  </div>
</li>