accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('confirm/', views.confirm_email, name='confirm_email'),
    path('confirm/sent/', views.email_confirm_sent, name='email_confirm_sent'),

    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('tag/<int:tag_pk>', views.article_list, name='article_list_by_tag'),
    path('', views.article_list, name='article_list'),
    path('create/', views.article_create, name='article_create'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
    path('<int:pk>/update/', views.article_update, name='article_update'),
    path('<int:pk>/delete/', views.article_delete, name='article_delete'),

    path('<int:article_pk>/comment/create/', views.comment_create, name='comment_create'),

    path('<int:pk>/like/', views.article_like, name='article_like'),
]

piro_remind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Tag(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(
        max_length=30,
        verbose_name='제목',
    )
    content = models.TextField(verbose_name='내용')

    liker_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='liked_article_set',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # m2m 에서 blank=True 설정하면 모델폼에서 폼 필드 렌더링할 때
    # required 옵션이 빠짐.
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return '{0}.{1}'.format(self.pk, self.title)

    def get_absolute_url(self):
        return reverse('core:article_detail', kwargs={
            'pk': self.pk,
        })


class Comment(models.Model):
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    content = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

core/forms.py
from django import forms

from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('liker_set', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('article', 'author', )

    # def __init__(self, *args, **kwargs):
    #     self.user = kwargs.pop('user')
    #     self.article = kwargs.pop('article')
    #     super().__init__(*args, **kwargs)

    # def clean(self):
    #     comment_count = self.user.comment_set.filter(article=self.article).count()
    #     if comment_count >= 5:
    #         raise forms.ValidationError('댓글은 5회만 남기실 수 있습니다.')

    # def save(self):
    #     comment = super().save(commit=False)
    #     comment.article = self.article
    #     comment.author = self.user
    #     comment.save()
    #     return comment

core/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.urls import reverse
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string

from .models import Article, Tag
from .forms import ArticleForm, CommentForm


MAX_COMMENT_COUNT = 100


def article_list(request, tag_pk=None):
    if tag_pk is not None:
        article_list = Article.objects.filter(tag__pk=tag_pk)
        # get_object_or_404 사용하는게 좋음.
        try:
            tag = Tag.objects.get(pk=tag_pk)
        except Tag.DoesNotExist:
            raise Http404('없는 Tag입니다.')
    else:
        article_list = Article.objects.all()
        tag = None

    ctx = {
        'article_list': article_list,
        'tag_list': Tag.objects.all(),
        'tag_selected': tag,
    }
    return render(request, 'core/article_list.html', ctx)


# @login_required
# def article_detail(request, pk):
#     article = get_object_or_404(Article, pk=pk)
#     comment_form = CommentForm(
#         request.POST or None,
#         article=article,
#         user=request.user,
#     )
#     if request.method == "POST" and comment_form.is_valid():
#         comment_form.save()
#         return redirect(article.get_absolute_url())

#     ctx = {
#         'article': article,
#         'comment_form': comment_form,
#         'did_like_article': article.liker_set.filter(pk=request.user.pk),
#     }

#     return render(request, 'core/article_detail.html', ctx)


@login_required
def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_count = article.comment_set.filter(author=request.user).count()
    ctx = {
        'article': article,
        'comment_form': CommentForm(),
        'did_like_article': article.liker_set.filter(pk=request.user.pk),
        'can_write_comment': comment_count < MAX_COMMENT_COUNT,
    }
    return render(request, 'core/article_detail.html', ctx)


@login_required
def comment_create(request, article_pk):
    if request.POST:
        article = Article.objects.get(pk=article_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()

            return render(request, 'core/comment.html', {
                'comment': comment,
            })

    return HttpResponse(status=405)


@login_required
def article_create(request):
    form = ArticleForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


@login_required
def article_update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = ArticleForm(request.POST or None, instance=article)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


# 이렇게 하나로 쓸 수도 있다. 상황에 맞게 하면 됨.
@login_required
def article_create_or_update(request, pk=None):
    if pk is not None:
        article = get_object_or_404(Article, pk=pk)
    else:
        article = None
    form = ArticleForm(request.POST or None, instance=article)

    if request.method == 'POST' and form.is_valid():
        article = form.save()
        return redirect(article.get_absolute_url())

    ctx = {
        'form': form,
    }

    return render(request, 'core/article_create.html', ctx)


@login_required
def article_delete(request, pk):
    if request.method == "POST":
        article = get_object_or_404(Article, pk=pk)
        article.delete()
        return redirect(reverse('core:article_list'))
    else:
        return HttpResponse(status=400)


@login_required
def article_like(request, pk):
    if request.method == "POST":
        article = get_object_or_404(Article, pk=pk)

        if request.user.liked_article_set.filter(pk=pk).exists():
            article.liker_set.remove(request.user)
        else:
            article.liker_set.add(request.user)

        ctx = {
            'did_like_article': article.liker_set.filter(pk=request.user.pk).exists(),
            'article': article,
        }
        return render(request, 'core/article_like_button.html', ctx)

    else:
        return HttpResponse(status=400)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <title>블로그 - {{ pk }} 번째 게시물</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="{% static 'css/core.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/accounts.css' %}" rel="stylesheet" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="{% static 'js/ajax_settings.js' %}"></script>
    <script src="{% static 'js/core_event.js' %}"></script>

</head>
<body>
    <header>

        <nav>
          <div class="nav-wrapper">
            <a href="/" class="brand-logo" style="margin-left: 10px;">우철's 블로그</a>
            <ul class="right hide-on-med-and-down">
                {% if request.user.is_authenticated %}
                <li>
                    <a class="dropdown-button" href="#!" data-activates="dropdown_for_login_user">{{ request.user }}<i class="material-icons right">arrow_drop_down</i></a>

                    <ul id="dropdown_for_login_user" class="dropdown-content">
                        <li><a href="{% url 'accounts:profile_detail' request.user.username %}">프로필 보기</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Log out..</a></li>
                    </ul>

                </li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
                <li><a href="{% url 'accounts:login' %}">로그인</a></li>
                {% endif %}
            </ul>
            <ul id="slide-out" class="side-nav">
                {% if request.user.is_authenticated %}
                <li>
                    <div class="user-view">
                        <div class="background"></div>
                        <a href="#!user"><img class="circle" src="{{ request.user.profile.image_url }}"></a>
                        <a href="#!name"><span class="white-text name">{{ request.user }}</span></a>
                        <a href="#!email"><span class="white-text email">{{ request.user.email }}</span></a>
                    </div>
                </li>
                <li><a href="{% url 'accounts:profile_detail' request.user.username %}">프로필 보기</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log out..</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">로그인</a></li>
                <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
                {% endif %}
            </ul>
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
            <script>
                $(".button-collapse").sideNav();
            </script>
          </div>
        </nav>

    </header>

    <main class="container" style="margin: 50px auto;">
        {% block content %}{% endblock %}
    </main>

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">우철's 블로그</h5>
            <p class="grey-text text-lighten-4">piro_remind version입니다.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">강의 GitHub Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="https://github.com/dlkorea/piro/" target="_blank">piro</a></li>
              <li><a class="grey-text text-lighten-3" href="https://github.com/dlkorea/piro_remind/" target="_blank">piro_remind</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        Copyright 2018. 정우철, All rights reserved.
        <a class="grey-text text-lighten-4 right" href="https://github.com/dlkorea/" target="_blank">강사 GitHub</a>
        </div>
      </div>
    </footer>
</body>
</html>